/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 basketball_court.glb --transform --types 
Files: basketball_court.glb [428.92KB] > basketball_court-transformed.glb [81.66KB] (81%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_5: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_31: THREE.Mesh;
	};
	materials: {
		PaletteMaterial001: THREE.MeshStandardMaterial;
		["Material.002"]: THREE.MeshStandardMaterial;
		PaletteMaterial002: THREE.MeshStandardMaterial;
	};
};

export function Model(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/basketball_court-transformed.glb"
	) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_5.geometry}
				material={materials.PaletteMaterial001}
				position={[0, 0.1, 0]}
			/>
			<mesh
				geometry={nodes.Object_17.geometry}
				material={materials["Material.002"]}
				position={[0, 0.135, 0]}
			/>
			<mesh
				geometry={nodes.Object_31.geometry}
				material={materials.PaletteMaterial002}
				position={[0, 0.1, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/models/basketball_court-transformed.glb");
