"use client";

import "./globals.css";

export const metadata = {
	title: "André Elias - Software Engineer",
	description: "Generated by create next app",
};

import { Chakra_Petch } from "next/font/google";
import Script from "next/script";

const chakraPetch = Chakra_Petch({
	subsets: ["latin"],
	weight: ["500", "700"],
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={chakraPetch.className}>{children}</body>
			<Script
				src="https://game-cdn.poki.com/scripts/v2/poki-sdk.js"
				strategy="beforeInteractive"
			/>
		</html>
	);
}
