import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "André Elias - Software Engineer",
	description: "Generated by create next app",
};

import { Chakra_Petch } from "next/font/google";

const chakraPetch = Chakra_Petch({
	subsets: ["latin"],
	weight: ["500", "700"],
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={chakraPetch.className}>{children}</body>
		</html>
	);
}
