/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ball.glb --transform 
Files: ball.glb [82.28KB] > ball-transformed.glb [7.75KB] (91%)
Author: chroma3d (https://sketchfab.com/vendol21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-cartoon-basketball-ball-free-555627427c054e3fa163a57f540e1b34
Title: Low Poly Cartoon Basketball Ball Free
*/
import { useGLTF } from "@react-three/drei";

export function BallMesh(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/ball-transformed.glb") as any;
  return (
    <group name="ball" {...props} dispose={null}>
      <mesh
        geometry={nodes.BasketballBall_MainColor_0.geometry}
        material={materials.MainColor}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.BasketballBall_Lines_0.geometry}
        material={materials.Lines}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/models/ball-transformed.glb");
