/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 basketball_court.glb --transform 
Files: basketball_court.glb [18.79MB] > basketball_court-transformed.glb [1.3MB] (93%)
Author: Klieg3D (https://sketchfab.com/Klieg3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-court-d2ea5bc76e094f1a9e6aa15891bd6885
Title: Basketball Court
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function CourtMesh(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/models/basketball_court-transformed.glb"
	) as any;
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.PaletteMaterial001}
				position={[0, 0.1, 0]}
			/>
			<mesh
				geometry={nodes.Object_8.geometry}
				material={materials.PaletteMaterial002}
				position={[0, 0.1, 0]}
			/>
			<mesh
				geometry={nodes.Object_17.geometry}
				material={materials["Material.002"]}
				position={[0, 0.135, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/models/basketball_court-transformed.glb");
